version: "3.8"
services:
  client:
    container_name: client
    build:
      context: ./packages/client
    ports:
      - 3000:3000
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: ./packages/api
    ports:
      - 4000:4000
    depends_on:
      - database
  database:
    container_name: database
    image: mongo
    ports:
      - 27017:27017
